import { ArrowRight, Check, Clock3, Package, ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ProductArt } from "./ProductArt";
import type { PersistedOrder } from "@/lib/shopEx";
import { money } from "@/lib/shopEx";

function statusCopy(status: PersistedOrder["status"]) {
  if (status === "captured") return { label: "Payment confirmed", confirmed: true };
  if (status === "failed") return { label: "Payment failed", confirmed: false };
  if (status === "verified") return { label: "Waiting for confirmation", confirmed: false };
  return { label: "Payment processing", confirmed: false };
}

export function OrderConfirmation({ order, onContinue, onViewOrder }: { order: PersistedOrder; onContinue: () => void; onViewOrder: () => void }) {
  const item = order.product;
  if (!item) return null;
  return <section className="mx-auto max-w-2xl text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-emerald-600"><Check className="h-8 w-8" /></div><p className="mt-6 text-sm font-semibold uppercase tracking-[.16em] text-emerald-600">Payment confirmed</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] text-slate-950 sm:text-5xl">You’re all set.</h1><p className="mx-auto mt-4 max-w-lg text-slate-500">Your payment was confirmed through the provider and recorded with this order.</p><div className="mt-8 overflow-hidden rounded-[22px] border border-slate-200 bg-white text-left shadow-[0_20px_60px_rgba(15,23,42,.06)]"><div className="flex gap-4 p-5 sm:p-6"><div className="w-32 shrink-0 sm:w-44"><ProductArt item={item} /></div><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-[.12em] text-slate-400">Order confirmed</p><h2 className="mt-1 text-xl font-semibold text-slate-950">{item.name}</h2><p className="mt-2 text-2xl font-semibold text-violet-700">{money(order.amount / 100)}</p></div></div><div className="grid gap-3 border-t border-slate-100 bg-slate-50 p-5 text-sm sm:grid-cols-2"><div><p className="text-xs text-slate-400">Order ID</p><p className="mt-1 font-medium text-slate-800">{order.orderId}</p></div><div><p className="text-xs text-slate-400">Status</p><p className="mt-1 flex items-center gap-1.5 font-medium text-emerald-700"><Check className="h-4 w-4" />Payment confirmed</p></div></div></div><div className="mt-7 flex flex-col gap-3 sm:flex-row sm:justify-center"><Button onClick={onViewOrder} variant="outline" className="h-11 rounded-[12px] border-slate-200 text-slate-600 hover:bg-slate-50"><Package className="mr-2 h-4 w-4" />View order</Button><Button onClick={onContinue} className="h-11 rounded-[12px] bg-violet-600 font-semibold text-white hover:bg-violet-700">Continue shopping<ArrowRight className="ml-2 h-4 w-4" /></Button></div></section>;
}

export function OrderHistory({ orders, onViewOrder }: { orders: PersistedOrder[]; onViewOrder: (orderId: string) => void }) {
  return <section className="mx-auto max-w-3xl"><div className="mb-8"><p className="text-sm font-semibold uppercase tracking-[.16em] text-violet-600">Your ShopEx</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.05em] text-slate-950">Orders</h1><p className="mt-2 text-slate-500">A clear record of purchases you approved.</p></div>{orders.length ? <div className="space-y-4">{orders.map((order) => { const item = order.product; const status = statusCopy(order.status); return <div key={order.orderId} className="overflow-hidden rounded-[20px] border border-slate-200 bg-white shadow-[0_18px_50px_rgba(15,23,42,.05)]"><div className="flex items-center gap-4 p-5 sm:p-6">{item ? <div className="h-20 w-20 shrink-0"><ProductArt item={item} compact /></div> : <div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-[14px] bg-slate-50"><Package className="h-6 w-6 text-slate-400" /></div>}<div className="min-w-0 flex-1"><p className="text-lg font-semibold text-slate-950">{item?.name ?? "Order record"}</p><p className="mt-1 text-sm text-slate-500">{money(order.amount / 100)} · {order.orderId}</p><div className={`mt-3 inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${status.confirmed ? "bg-emerald-50 text-emerald-700" : order.status === "failed" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{status.confirmed ? <Check className="h-3.5 w-3.5" /> : <Clock3 className="h-3.5 w-3.5" />}{status.label}</div></div><Button onClick={() => onViewOrder(order.orderId)} variant="outline" size="sm" className="hidden rounded-[10px] border-slate-200 sm:flex">View<ArrowRight className="ml-2 h-3.5 w-3.5" /></Button></div><div className="flex items-center gap-3 border-t border-slate-100 px-5 py-3 text-xs text-slate-500 sm:px-6"><ShoppingBag className="h-4 w-4 text-violet-500" />Created {new Date(order.createdAt).toLocaleString()}</div></div>; })}</div> : <div className="rounded-[20px] border border-dashed border-slate-200 bg-white p-8 text-center text-sm leading-6 text-slate-500">You have no orders yet. Once a payment is confirmed, it will appear here.</div>}</section>;
}
