import { Bell, Check, LogOut, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export function NotificationCenter() {
  const utils = trpc.useUtils();
  const query = trpc.account.notifications.useQuery({ limit: 20 });
  const markRead = trpc.account.markNotificationRead.useMutation({ onSuccess: () => utils.account.notifications.invalidate() });
  const unread = query.data?.filter((item) => !item.readAt).length ?? 0;
  return <section className="mt-8 rounded-[22px] border border-slate-200 bg-white p-6 shadow-[0_14px_40px_rgba(15,23,42,.04)] sm:p-7">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-600">Inbox</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em] text-slate-950">Account notifications</h2><p className="mt-1 text-sm text-slate-500">Payment and order updates are kept here when your preferences allow them.</p></div><div className="flex items-center gap-2 rounded-full bg-violet-50 px-3 py-2 text-xs font-semibold text-violet-700"><Bell className="h-3.5 w-3.5" />{unread} unread</div></div>
    {query.isLoading ? <div className="mt-6 h-24 animate-pulse rounded-[16px] bg-slate-50" /> : query.isError ? <div className="mt-5 rounded-[14px] bg-red-50 p-4 text-sm text-red-800">Notifications are temporarily unavailable. {query.error.message}</div> : query.data?.length ? <div className="mt-5 divide-y divide-slate-100">{query.data.map((item) => <div key={item.id} className={`flex items-start gap-3 py-4 ${item.readAt ? "opacity-65" : ""}`}><div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><Check className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{item.title}</p><p className="mt-1 text-sm leading-5 text-slate-500">{item.body}</p><p className="mt-1 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</p></div>{!item.readAt && <Button variant="outline" size="sm" disabled={markRead.isPending} onClick={() => markRead.mutate({ id: item.id })} className="rounded-full border-slate-200 text-xs">Mark read</Button>}</div>)}</div> : <div className="mt-5 rounded-[14px] border border-dashed border-slate-200 p-6 text-center text-sm text-slate-500">No account notifications yet.</div>}
  </section>;
}

export function SecurityPanel() {
  const utils = trpc.useUtils();
  const query = trpc.account.securityOverview.useQuery();
  const revoke = trpc.account.revokeAllSessions.useMutation({ onSuccess: () => utils.account.securityOverview.invalidate() });
  const revokeOne = trpc.account.revokeSession.useMutation({ onSuccess: () => utils.account.securityOverview.invalidate() });
  return <section className="mt-8 rounded-[22px] border border-slate-200 bg-white p-6 shadow-[0_14px_40px_rgba(15,23,42,.04)] sm:p-7"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-[12px] bg-emerald-50 text-emerald-700"><ShieldCheck className="h-5 w-5" /></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-emerald-600">Security</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em] text-slate-950">Session controls</h2><p className="mt-1 text-sm text-slate-500">Revoke all existing ShopEx sessions if you suspect an account was left open.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-[14px] bg-slate-50 p-4"><p className="text-xs uppercase tracking-[.12em] text-slate-400">Last sign-in</p><p className="mt-2 text-sm font-semibold text-slate-800">{query.data?.lastSignedIn ? new Date(query.data.lastSignedIn).toLocaleString() : "Loading…"}</p></div><div className="rounded-[14px] bg-slate-50 p-4"><p className="text-xs uppercase tracking-[.12em] text-slate-400">Session policy</p><p className="mt-2 text-sm font-semibold text-slate-800">OAuth expiry + manual revocation</p></div></div><div className="mt-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Recent sessions</p><div className="mt-3 space-y-2">{query.data?.sessions?.length ? query.data.sessions.map((session) => <div key={session.id} className="flex flex-wrap items-center gap-3 rounded-[12px] bg-slate-50 p-3"><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-800">{session.deviceLabel}</p><p className="mt-1 text-xs text-slate-500">Started {new Date(session.createdAt).toLocaleString()} · Last seen {new Date(session.lastSeenAt).toLocaleString()}</p></div>{session.revokedAt ? <span className="text-xs font-medium text-red-600">Revoked</span> : <Button size="sm" variant="outline" disabled={revokeOne.isPending} onClick={() => revokeOne.mutate({ id: session.id })} className="rounded-full border-red-200 text-xs text-red-700">Revoke</Button>}</div>) : <p className="rounded-[12px] bg-slate-50 p-3 text-sm text-slate-500">No active session records yet. A new session will appear after your next sign-in.</p>}</div></div><Button variant="outline" disabled={revoke.isPending} onClick={() => revoke.mutate()} className="mt-5 rounded-[12px] border-red-200 text-red-700 hover:bg-red-50"><LogOut className="mr-2 h-4 w-4" />{revoke.isPending ? "Revoking sessions…" : "Sign out all sessions"}</Button>{revoke.isSuccess && <p className="mt-3 text-sm font-medium text-emerald-700">All existing sessions were revoked. You may need to sign in again on other devices.</p>}</section>;
}
